kill-switch: pause
save-history: True
# angry-keys: sysrq
# key: 57, 57, 86
# key: [
#     "(57, 57, 86)", # Map space to (non-existent) <>| key
#     # "(57, 57, 29)",
#     # "(33, 33, 42)",
#     # "(34, 34, 29)",
#     # "(35, 35, 29)",
#     # "(36, 36, 42)",

#     "(33, 33, 29)", # f to lctrl
#     "(36, 36, 29)", # j to lctrl

#     # "(32, 32, 29)",
#     # "(37, 37, 29)",
#     ]
key: [
    # "100, 28, 100", # ralt -> ralt/enter
    # "56, 15, 100", # lalt -> ralt/tab
    "space, space, leftctrl", # space -> lctrl
    "leftalt, tab, leftalt",
    # "33, 33, 70", # f -> sclk (mod5)
    # "36, 36, 70", # j -> sclk (mod5)
    "f, f, scrolllock", # f -> sclk (mod5)
    "j, j, scrolllock", # j -> sclk (mod5)
    # "33, 33, 58", # f -> caps
    # "36, 36, 58", # j -> caps, important not to map to left because of lock
    # "5, 5, 56", # 4 -> lalt
    # "10, 10, 56", # 9 -> lalt
    ]
# pre-emptive-mods: [LEFTSHIFT, RIGHTSHIFT, LEFTALT, RIGHTALT] # lshift, rshift, lalt, ralt
# pre-emptive-mods: [leftshift, rightshift, leftctrl, rightctrl] # lshift, rshift, lalt, ralt
pre-emptive-mods: [leftalt, leftshift] # lshift, rshift, lalt, ralt
ignore: [btn_tool_finger, btn_touch]
repeat-timeout: 200
repeat-keys: [f, j, space]
idle-timeout: 800
idle-keys: [f, j, space, leftalt]
